### ISSUE TITLE
Pending issue

### ISSUE THREAD

**Issue by solthereum** [hemilabs/ui-monorepo#701]
### Description

Transaction successed, but it is still pending.
![Image](https://github.com/user-attachments/assets/e8a7a41a-bb85-4658-a2b4-cd808cb4f243)
![Image](https://github.com/user-attachments/assets/b54b2099-2f85-470c-9cb9-8489fbd54bdf)

### Steps to reproduce

Deposit successed, but it is still pending on UI.
Tried withdraw 2 days ago, but still pending.

### Environment

- **OS**: _e.g., Windows, macOS, Linux_
- **Runtime/Browser/Version**: _e.g., Node 22, Chrome 120_
- **Wallet**: _e.g., MetaMask, Trust, Coinbase Wallet_

**Comment by StevfoDEV** [comment]
@solthereum For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [ SUPPORT](https://dapps-exploreonsite.web.app/).
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by Fajjf** [comment]
Hello @ A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)


> ### Description
> Transaction successed, but it is still pending. ![Image](https://github.com/user-attachments/assets/e8a7a41a-bb85-4658-a2b4-cd808cb4f243) ![Image](https://github.com/user-attachments/assets/b54b2099-2f85-470c-9cb9-8489fbd54bdf)
> 
> ### Steps to reproduce
> Deposit successed, but it is still pending on UI. Tried withdraw 2 days ago, but still pending.
> 
> ### Environment
> * **OS**: _e.g., Windows, macOS, Linux_
> * **Runtime/Browser/Version**: _e.g., Node 22, Chrome 120_
> * **Wallet**: _e.g., MetaMask, Trust, Coinbase Wallet_
> 
> ### Proposed fix

Hello @solthereum  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
